links:
  rails:
    url: "https://www.railstutorial.org"
    book: "https://www.railstutorial.org/book"
    help: "https://www.railstutorial.org/help"
value:
  max_user_name: 50
  max_user_email: 255
  valid_email: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
